from .prompts import (
    DEFAULT_INSTRUCTION,
    GENERIC_TEXTBOOK_EXTRACTION_INSTRUCTION,
    MATH_EDU_SCORE_INSTRUCTION,
    MATH_EXTRACTION_INSTRUCTION,
    MATH_GRADE_LEVEL_INSTRUCTION,
    MATH_TOPIC_INSTRUCTION,
    WEBPAGE_EDU_SCORE_INSTRUCTION,
)

__all__ = [
    "DEFAULT_INSTRUCTION",
    "GENERIC_TEXTBOOK_EXTRACTION_INSTRUCTION",
    "MATH_EDU_SCORE_INSTRUCTION",
    "MATH_EXTRACTION_INSTRUCTION",
    "MATH_GRADE_LEVEL_INSTRUCTION",
    "MATH_TOPIC_INSTRUCTION",
    "WEBPAGE_EDU_SCORE_INSTRUCTION",
]
